In [ ]:
# Answer 1
import numpy as np

arr1 = np.arange(2,51,3)
print(arr1)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [ ]:
# Answer 2

list1=[]
for i in range(0,5):
  ele = int(input())
  list1.append(ele)

list2=[]
for j in range(0,5):
  ele = int(input())
  list2.append(ele)

#print(list1)
#print(list2)
a1 = np.array(list1)
a2 = np.array(list2)

a3 = np.concatenate((a1, a2))
print(a3)  # Concatenated 2 list as array

print(np.sort(a3))  # Sorted array

1
2
3
4
5
22
33
55
44
11
[ 1  2  3  4  5 22 33 55 44 11]
[ 1  2  3  4  5 11 22 33 44 55]


In [ ]:
# Answer 3
#a = np.arange(3)

my_array = np.array([])
a=int(input())  # Size of array
for i in range(a):
    ele=int(input())
    my_array.append(ele)

print(a.ndim)
print(a.shape)


In [ ]:
# Answer 4

one_d = np.array([1, 2, 3, 4])
print(one_d)

two_d = np.reshape(one_d, (-1, 2))
print(two_d)


[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
# Answer 5

a1 = np.array([[1,2], [3,4]])
a2 = np.array([[5,6], [7,8]])

print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Answer 6

a = np.array([1, 1, 2, 2, 3, 4, 5, 5])
unique = np.unique(a)
print(unique)
print(len(unique))



[1 2 3 4 5]
5
